const products = [
  {
    id: 1,
    name: "Men's Shirt",
    price: 75,
    image: "images/p1.png",
    alt: "shirt 1",
  },
  {
    id: 2,
    name: "Men's Shirt",
    price: 80,
    image: "images/p2.png",
    alt: "shirt 2",
  },
  {
    id: 3,
    name: "Women's Dress",
    price: 68,
    image: "images/p3.png",
    alt: "dress 1",
  },
  {
    id: 4,
    name: "Women's Dress",
    price: 70,
    image: "images/p4.png",
    alt: "dress 2",
  },
  {
    id: 5,
    name: "Women's Dress",
    price: 75,
    image: "images/p5.png",
    alt: "dress 3",
  },
  {
    id: 6,
    name: "Women's Dress",
    price: 58,
    image: "images/p6.png",
    alt: "drees 4",
  },
  {
    id: 7,
    name: "Women's Dress",
    price: 80,
    image: "images/p7.png",
    alt: "dress 5",
  },
  {
    id: 8,
    name: "Men's Shirt",
    price: 65,
    image: "images/p8.png",
    alt: "shirt 3",
  },
  {
    id: 9,
    name: "Men's Shirt",
    price: 65,
    image: "images/p9.png",
    alt: "shirt 4",
  },
  {
    id: 10,
    name: "Men's Shirt",
    price: 65,
    image: "images/p10.png",
    alt: "shirt 5",
  },
  {
    id: 11,
    name: "Men's Shirt",
    price: 67,
    image: "images/p11.png",
    alt: "shirt 6",
  },
  {
    id: 12,
    name: "Women's Dress",
    price: 85,
    image: "images/p12.png",
    alt: "dress 6",
  },
];
